export default [
  {
    id: 'community-1',
    name: 'Batang 90s Toys',
    url: 'https://www.facebook.com/groups/656162135221029',
    type: 'group',
    description: 'Facebook group for community discussions and collecting.',
    image: '',
    vip: false,
    status: 'published',
    position: 0,
  },
  {
    id: 'community-2',
    name: 'Pinoy Teks Group',
    url: 'https://www.facebook.com/groups/pinoyteks',
    type: 'group',
    description: 'Facebook group for community discussions and collecting.',
    image: '',
    vip: false,
    status: 'published',
    position: 1,
  },
  {
    id: 'community-3',
    name: 'Pinoy Teks Trading',
    url: 'https://www.facebook.com/groups/469352094273958/',
    type: 'group',
    description: 'Facebook group for community discussions and collecting.',
    image: '',
    vip: false,
    status: 'published',
    position: 2,
  },
  {
    id: 'community-4',
    name: 'PINOY TEKS GROUP PILIPINAS BUY N SELL',
    url: 'https://www.facebook.com/groups/297518979575811/',
    type: 'group',
    description: 'Facebook group for community discussions and collecting.',
    image: '',
    vip: false,
    status: 'published',
    position: 3,
  },
  {
    id: 'community-5',
    name: 'Photo "toyz" ni RIVA',
    url: 'https://www.facebook.com/profile.php?id=100063554006918',
    type: 'page',
    description: 'Discover posts and updates from this community page.',
    image: '',
    vip: false,
    status: 'published',
    position: 4,
  },
  {
    id: 'community-6',
    name: 'Jamesvintagecollection - JVC',
    url: 'https://www.facebook.com/JVCJamesVintageCollection',
    type: 'page',
    description: 'Discover posts and updates from this community page.',
    image: '',
    vip: false,
    status: 'published',
    position: 5,
  },
  {
    id: 'community-7',
    name: 'Alvin Guanizo',
    url: 'https://www.facebook.com/alvin.retro.2024',
    type: 'profile',
    description:
      'Seller and collector recommended by the Teksboy community curator.',
    image: '',
    vip: false,
    status: 'published',
    position: 6,
  },
  {
    id: 'community-8',
    name: 'Robert Bryan Catalan',
    url: 'https://www.facebook.com/robbie0814',
    type: 'profile',
    description:
      'Seller and collector recommended by the Teksboy community curator.',
    image: '',
    vip: false,
    status: 'published',
    position: 7,
  },
  {
    id: 'community-9',
    name: 'Pembo ni Yohan',
    url: 'https://www.facebook.com/johnpaulendrina34',
    type: 'profile',
    description:
      'Seller and collector recommended by the Teksboy community curator.',
    image: '',
    vip: false,
    status: 'published',
    position: 8,
  },
  {
    id: 'community-10',
    name: 'Ronnie Mercado',
    url: 'https://www.facebook.com/james.harden.266812',
    type: 'profile',
    description:
      'Seller and collector recommended by the Teksboy community curator.',
    image: '',
    vip: false,
    status: 'published',
    position: 9,
  },
  {
    id: 'community-11',
    name: 'Quirino Denzel Pajares',
    url: 'https://www.facebook.com/quirino.pajares',
    type: 'profile',
    description:
      'Seller and collector recommended by the Teksboy community curator.',
    image: '',
    vip: false,
    status: 'published',
    position: 10,
  },
  {
    id: 'community-12',
    name: 'Jessper Bryan Sarmiento',
    url: 'https://www.facebook.com/jessperbryan.sarmiento.948',
    type: 'profile',
    description:
      'Seller and collector recommended by the Teksboy community curator.',
    image: '',
    vip: false,
    status: 'published',
    position: 11,
  },
  {
    id: 'community-13',
    name: 'Rex Redor',
    url: 'https://www.facebook.com/jon.red.79',
    type: 'profile',
    description:
      'Seller and collector recommended by the Teksboy community curator.',
    image: '',
    vip: true,
    status: 'published',
    position: 12,
  },
  {
    id: 'community-14',
    name: 'James Gensemer',
    url: 'https://www.facebook.com/themaclife702',
    type: 'profile',
    description:
      'Seller and collector recommended by the Teksboy community curator.',
    image: '',
    vip: true,
    status: 'published',
    position: 13,
  },
];
