-- Teksboy initial schema. Apply once to a new Supabase project.
begin;
create table public.categories(id text primary key,name text not null,position integer not null default 0);
create table public.sets(id text primary key,category_id text not null references public.categories(id) on delete restrict,name text not null,cover text not null,position integer not null default 0,status text not null default 'draft' check(status in ('draft','published','archived')));
create table public.cards(id text primary key,set_id text not null references public.sets(id) on delete restrict,number integer not null check(number>0),image text not null,unique(set_id,number));
create table public.tracks(id text primary key,category_id text not null references public.categories(id) on delete restrict,title text not null,url text not null,position integer not null default 0);
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text not null default '',status text not null default 'active' check(status in ('active','suspended')),created_at timestamptz not null default now());
create table public.admin_users(user_id uuid primary key references public.profiles(id) on delete cascade);
create table public.checklists(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,set_id text not null references public.sets(id) on delete restrict,created_at timestamptz not null default now(),unique(user_id,set_id));
create table public.checklist_cards(checklist_id uuid not null references public.checklists(id) on delete cascade,card_id text not null references public.cards(id) on delete restrict,collected_at timestamptz not null default now(),primary key(checklist_id,card_id));
create table public.audit_log(id uuid primary key default gen_random_uuid(),actor_id uuid,table_name text not null,action text not null,record_id text,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());
create index on public.sets(category_id);create index on public.cards(set_id);create index on public.tracks(category_id);create index on public.checklists(user_id);create index on public.checklist_cards(card_id);create index on public.audit_log(created_at desc);
create function public.is_active() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid() and status='active'); $$;
create function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.admin_users a join public.profiles p on p.id=a.user_id where a.user_id=auth.uid() and p.status='active'); $$;
revoke all on function public.is_active() from public;revoke all on function public.is_admin() from public;grant execute on function public.is_active(),public.is_admin() to anon,authenticated;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','Collector'));return new;end; $$;
revoke all on function public.handle_new_user() from public;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create function public.validate_checklist_card() returns trigger language plpgsql set search_path='' as $$ begin if not exists(select 1 from public.checklists l join public.cards c on c.set_id=l.set_id where l.id=new.checklist_id and c.id=new.card_id) then raise exception 'Card does not belong to checklist set';end if;return new;end; $$;
create trigger validate_card before insert or update on public.checklist_cards for each row execute function public.validate_checklist_card();
-- Prevent catalog edits from moving cards or checklist records between sets.
create function public.protect_identity() returns trigger language plpgsql set search_path='' as $$ begin if new.id<>old.id then raise exception 'IDs cannot change';end if;if tg_table_name='cards' and new.set_id<>old.set_id then raise exception 'Card set cannot change';end if;if tg_table_name='checklists' and (new.set_id<>old.set_id or new.user_id<>old.user_id) then raise exception 'Checklist ownership cannot change';end if;return new;end; $$;
create trigger stable_card before update on public.cards for each row execute function public.protect_identity();
create trigger stable_checklist before update on public.checklists for each row execute function public.protect_identity();
create function public.log_admin_change() returns trigger language plpgsql security definer set search_path='' as $$ begin if public.is_admin() then insert into public.audit_log(actor_id,table_name,action,record_id,old_data,new_data) values(auth.uid(),tg_table_name,tg_op,coalesce(to_jsonb(new)->>'id',to_jsonb(old)->>'id',to_jsonb(new)->>'checklist_id',to_jsonb(old)->>'checklist_id'),case when tg_op<>'INSERT' then to_jsonb(old) end,case when tg_op<>'DELETE' then to_jsonb(new) end);end if;return coalesce(new,old);end; $$;
revoke all on function public.log_admin_change() from public;
do $$ declare t text;begin foreach t in array array['categories','sets','cards','tracks','profiles','admin_users','checklists','checklist_cards','audit_log'] loop execute format('alter table public.%I enable row level security',t);end loop;foreach t in array array['categories','sets','cards','tracks','profiles','checklists','checklist_cards'] loop execute format('create trigger audit_changes after insert or update or delete on public.%I for each row execute function public.log_admin_change()',t);end loop;end $$;
revoke all on public.categories,public.sets,public.cards,public.tracks,public.profiles,public.admin_users,public.checklists,public.checklist_cards,public.audit_log from anon,authenticated;
grant select on public.categories,public.sets,public.cards,public.tracks to anon,authenticated;
grant insert,update on public.categories,public.sets,public.cards,public.tracks to authenticated;
grant select,update on public.profiles to authenticated;
grant select on public.admin_users,public.audit_log to authenticated;
grant select,insert,update on public.checklists to authenticated;
grant select,insert,delete on public.checklist_cards to authenticated;
create policy categories_read on public.categories for select using(true);
create policy sets_read on public.sets for select using(status='published' or public.is_admin() or exists(select 1 from public.checklists l where l.set_id=sets.id and l.user_id=auth.uid()));
create policy cards_read on public.cards for select using(exists(select 1 from public.sets s where s.id=cards.set_id));
create policy tracks_read on public.tracks for select using(true);
do $$ declare t text;begin foreach t in array array['categories','sets','cards','tracks'] loop execute format('create policy admin_insert on public.%I for insert to authenticated with check(public.is_admin())',t);execute format('create policy admin_update on public.%I for update to authenticated using(public.is_admin()) with check(public.is_admin())',t);end loop;end $$;
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy profile_admin_update on public.profiles for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy admin_read on public.admin_users for select to authenticated using(user_id=auth.uid() or public.is_admin());
create policy audit_read on public.audit_log for select to authenticated using(public.is_admin());
create policy checklist_read on public.checklists for select to authenticated using((user_id=auth.uid() and public.is_active()) or public.is_admin());
create policy checklist_insert on public.checklists for insert to authenticated with check(user_id=auth.uid() and public.is_active() and exists(select 1 from public.sets s where s.id=set_id and s.status='published'));
create policy checklist_update on public.checklists for update to authenticated using(user_id=auth.uid() and public.is_active()) with check(user_id=auth.uid() and public.is_active());
create policy owned_read on public.checklist_cards for select to authenticated using(exists(select 1 from public.checklists l where l.id=checklist_id and ((l.user_id=auth.uid() and public.is_active()) or public.is_admin())));
create policy owned_insert on public.checklist_cards for insert to authenticated with check(exists(select 1 from public.checklists l where l.id=checklist_id and ((l.user_id=auth.uid() and public.is_active()) or public.is_admin())));
create policy owned_delete on public.checklist_cards for delete to authenticated using(exists(select 1 from public.checklists l where l.id=checklist_id and ((l.user_id=auth.uid() and public.is_active()) or public.is_admin())));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('media','media',true,20971520,array['image/webp','image/png','image/jpeg','audio/mpeg','audio/ogg','audio/wav']);
create policy media_admin_insert on storage.objects for insert to authenticated with check(bucket_id='media' and public.is_admin());
create policy media_admin_update on storage.objects for update to authenticated using(bucket_id='media' and public.is_admin()) with check(bucket_id='media' and public.is_admin());
create policy media_read on storage.objects for select using(bucket_id='media');
commit;
