import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {Readable} from 'node:stream';import localCms,{openStore} from '../local/cms-plugin.mjs';
test('confirmed deletion is owner-scoped, account cleanup and activity access',async()=>{
const root=fs.mkdtempSync(path.join(os.tmpdir(),'teksboy-removal-'));fs.mkdirSync(path.join(root,'lib'));for(const f of ['categories','catalog'])fs.writeFileSync(path.join(root,'lib',f+'.json'),'[]');const store=openStore(root);let handler,close,cookie='';localCms().configureServer({config:{root},middlewares:{use:f=>handler=f},httpServer:{once:(_,f)=>close=f}});
async function call(url,data){let result,status;const req=Readable.from(data?[JSON.stringify(data)]:[]);Object.assign(req,{url,method:data?'POST':'GET',headers:{host:'localhost:3100',cookie,'content-type':'application/json'},socket:{remoteAddress:'127.0.0.1'}});const res={statusCode:200,setHeader(k,v){if(k==='Set-Cookie')cookie=(Array.isArray(v)?v[0]:v).split(';')[0]},end(t){status=res.statusCode;result=JSON.parse(t)}};await handler(req,res,()=>{});return {status,result};}
try{
store.put('collections',{id:'s',name:'Set',status:'published',cards:[{id:'a'}]});for(const id of ['local-demo','local-admin'])store.put('checklists',{id:id+':s',user_id:id,set_id:'s',owned:['a']});store.put('comments',{id:'own',author_id:'local-demo',owner:'local-admin',set:'',text:'Comment',cards:[],created_at:new Date().toISOString()});store.put('comments',{id:'reply',author_id:'local-admin',owner:'local-admin',set:'',parent:'own',text:'Reply',cards:[]});
await call('/__local/social/login',{id:'local-demo'});assert.equal((await call('/__local/activity')).status,400);assert.equal((await call('/__local/remove-comment',{id:'reply',confirm:true})).status,400);assert.equal((await call('/__local/remove-comment',{id:'own',confirm:true})).status,200);assert.equal(store.get('comments','reply').text,'Reply');
assert.equal((await call('/__local/social/comment',{owner:'local-admin',text:'x'.repeat(501)})).status,400);
assert.equal((await call('/__local/remove-checklist',{id:'s'})).status,400);assert.equal((await call('/__local/remove-checklist',{id:'s',confirm:true})).status,200);assert.ok(store.get('checklists','local-admin:s'));assert.equal(store.get('checklists','local-demo:s'),null);
assert.equal((await call('/__local/remove-account',{confirm:true})).status,200);assert.equal(store.get('users','local-demo').status,'deleted');assert.equal(store.get('users','local-demo').email,undefined);assert.equal((await call('/__local/social/login',{id:'local-demo'})).status,400);
store.put('users',{id:'second-super',name:'Second super',role:'Super Admin',status:'active'});await call('/__local/social/login',{id:'local-admin'});assert.equal((await call('/__local/remove-account',{confirm:true})).status,400);assert.equal((await call('/__local/save',{kind:'groups',row:{id:'g',name:'Test group',status:'published'}})).status,200);
const events=(await call('/__local/activity')).result.items;assert.ok(events.some(e=>e.category==='groups'&&e.target==='Test group'));assert.ok(events.some(e=>e.action==='Deleted account'));assert.equal(events.filter(e=>e.action==='Removed checklist').length,1);
}finally{close();store.db.close();fs.rmSync(root,{recursive:true,force:true});}
});
